language: node_js
node_js:
  - "4.0"
before_install:
  - sudo apt-get install libblas-dev
  - sudo apt-get install liblapack-dev
  - wget http://www.netlib.org/lapack/lapack-3.6.1.tgz
  - tar xvf lapack-3.6.1.tgz
  - cd lapack-3.6.1/
  - cmake -DCMAKE_INSTALL_PREFIX=~/.local -DLAPACKE=ON -DCBLAS=ON .
  - make install -j2 && ctest -j2 --output-on-failure --timeout 100
  - cd ..
install:
  - npm install
  - npm test
env:
  - CXX=g++-4.8
addons:
  code-climate:
    repo-token: 3723d8c83fad0d62970815c780582596b434c352fc64f6b6b3d72599540fb997
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports # cmake
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
    - cmake
    - cmake-data
    - gfortran
