language: node_js
node_js:
  - "4.0"
before_install:
  - sudo apt-get install libblas*
  - sudo apt-get install liblapack*
  - sudo apt-get install libgsl0-dev
#  - sudo apt-get install liblapacke-dev
  - wget http://www.netlib.org/lapack/lapack-3.8.0.tar.gz
  - tar xf lapack-3.8.0.tar.gz
  - mv ./lapack-3.8.0 ./lapack
  - mkdir lapack-build
  - cd lapack-build/
  - cmake -DCMAKE_INSTALL_PREFIX=/usr -DLAPACKE=ON -DCBLAS=ON -DBUILD_SHARED_LIBS=ON  ../lapack
#  - sudo make install -j2 && ctest -j2 --output-on-failure --timeout 100
  - sudo make install -j2
  - cd ..
#  - rm ./lapack-3.8.0.tar.gz
#  - rm -rf ./lapack
#  - rm -rf ./lapack-build
#  - export LD_LIBRARY_PATH=~/.local/lib/:${LD_LIBRARY_PATH}
#  - export CPATH=~/.local/include/:${CPATH}
install:
  - npm install
env:
  - CXX=g++-4.8
addons:
  code-climate:
    repo-token: 3723d8c83fad0d62970815c780582596b434c352fc64f6b6b3d72599540fb997
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports # cmake
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
    - cmake
    - cmake-data
    - gfortran
